services:
  stable-diffusion-webui:
    container_name: stable-diffusion-webui
    image: aauno/stable-diffusion-webui-docker:latest
    entrypoint: ["./webui.sh"]
    command: ["--skip-version-check","--allow-code","--enable-insecure-extension-access","--api","--listen","--xformers","--opt-channelslast", "--data-dir", "/stable-diffusion-webui/data"]
    volumes:
      - /opt/stable-diffusion-webui/data:/stable-diffusion-webui/data
    ports:
      - "7860:7860"    
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]